// Trace.h — WPP tracing definitions for iexdd.
//
// To start a trace session on the target machine:
//   tracelog -start iExtend -guid {B2A6B7C1-3E4D-5F60-8192-A3B4C5D6E7F8} \
//             -f iexdd.etl -level 5
//   <exercise the driver>
//   tracelog -stop iExtend
//   tracefmt iexdd.etl -o iexdd.txt
//
// GUID: {B2A6B7C1-3E4D-5F60-8192-A3B4C5D6E7F8}
// Registered in the driver's INF under the [WPP] section.

#pragma once

// WPP control GUID — must match tracelog invocations above.
// {B2A6B7C1-3E4D-5F60-8192-A3B4C5D6E7F8}
#define WPP_CONTROL_GUIDS \
    WPP_DEFINE_CONTROL_GUID( \
        iexddTraceGuid, \
        (B2A6B7C1, 3E4D, 5F60, 81, 92, A3, B4, C5, D6, E7, F8), \
        WPP_DEFINE_BIT(TRACE_DRIVER) \
        WPP_DEFINE_BIT(TRACE_DEVICE) \
        WPP_DEFINE_BIT(TRACE_QUEUE)  \
    )

#define WPP_FLAG_LEVEL_LOGGER(flag, level) \
    WPP_LEVEL_LOGGER(flag)
#define WPP_FLAG_LEVEL_ENABLED(flag, level) \
    (WPP_LEVEL_ENABLED(flag) && WPP_CONTROL(WPP_BIT_ ## flag).Level >= level)

// The TMH file is auto-generated by the WPP pre-processor at build time.
// It must be included after the WPP_CONTROL_GUIDS definition.
#include "iexdd.tmh"
