#!/bin/sh
# dkms-mok-enrollment.sh — SecureBoot MOK enrollment helper for iExtend
#
# This script is called from the iextend package postinst and from the
# iextend-evdi-dkms postinst after the MOK key has been generated by Plan 4's
# sign-key.sh.  It is idempotent: safe to run multiple times.
#
# Exit codes:
#   0 — enrollment initiated (or already enrolled, or SecureBoot disabled)
#   1 — MOK key missing; evdi-dkms install is incomplete
#
# The script must run as root (called from dpkg maintainer scripts which run
# as root).  It drops to interactive mode only when SecureBoot is enabled and
# the key is not yet enrolled.

set -eu

MOK_DIR="/var/lib/dkms/iextend-evdi/mok"
MOK_DER="${MOK_DIR}/MOK.der"

# ---------------------------------------------------------------------------
# Helper: detect SecureBoot state
# Returns 0 if SecureBoot is enabled, 1 if disabled, 2 if unknown.
# ---------------------------------------------------------------------------
secureboot_enabled() {
    # No EFI → legacy BIOS → no SecureBoot
    if [ ! -d /sys/firmware/efi ]; then
        return 1
    fi

    if command -v mokutil >/dev/null 2>&1; then
        sb_state=$(mokutil --sb-state 2>/dev/null || echo "unknown")
        case "$sb_state" in
            *"enabled"*)  return 0 ;;
            *"disabled"*) return 1 ;;
            *)            return 2 ;;
        esac
    fi

    # Fallback: read the SecureBoot EFI variable directly.
    # The variable value is a 5-byte structure; byte 4 (offset 4) is 1 = on.
    sb_var=$(find /sys/firmware/efi/efivars \
             -name 'SecureBoot-*' 2>/dev/null | head -1)
    if [ -n "$sb_var" ]; then
        sb_byte=$(od -An -tu1 -j 4 -N 1 "$sb_var" 2>/dev/null | tr -d ' \n')
        [ "$sb_byte" = "1" ] && return 0 || return 1
    fi

    return 2  # unknown
}

# ---------------------------------------------------------------------------
# Helper: check if MOK is already enrolled
# Returns 0 if enrolled, 1 if not (or if mokutil is unavailable).
# ---------------------------------------------------------------------------
mok_already_enrolled() {
    if ! command -v mokutil >/dev/null 2>&1; then
        return 1
    fi
    # Look for our DER key's SHA256 fingerprint in the enrolled list
    our_fp=$(openssl x509 -in "$MOK_DER" -inform DER \
             -fingerprint -sha256 -noout 2>/dev/null \
             | sed 's/sha256 Fingerprint=//' | tr -d ':' | tr '[:upper:]' '[:lower:]')
    if [ -z "$our_fp" ]; then
        return 1
    fi
    enrolled_fps=$(mokutil --list-enrolled 2>/dev/null \
                   | grep -i 'SHA256' | tr -d ':' | tr '[:upper:]' '[:lower:]') || true
    case "$enrolled_fps" in
        *"$our_fp"*) return 0 ;;
        *)           return 1 ;;
    esac
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

# Check MOK key exists (generated by evdi-dkms sign-key.sh in Plan 4)
if [ ! -f "$MOK_DER" ]; then
    echo "iExtend: MOK key not found at $MOK_DER." >&2
    echo "         The iextend-evdi-dkms package may not be installed yet." >&2
    echo "         Install iextend-evdi-dkms first, then run:" >&2
    echo "           dpkg-reconfigure iextend-evdi-dkms" >&2
    exit 1
fi

# Determine SecureBoot state
if secureboot_enabled; then
    SB_STATE="enabled"
elif [ $? -eq 1 ]; then
    SB_STATE="disabled"
else
    SB_STATE="unknown"
fi

case "$SB_STATE" in
    disabled|unknown)
        echo "iExtend: SecureBoot is ${SB_STATE} — MOK enrollment not required."
        exit 0
        ;;
esac

# SecureBoot is enabled.  Check whether key is already enrolled.
if mok_already_enrolled; then
    echo "iExtend: MOK key is already enrolled — nothing to do."
    exit 0
fi

# Check that mokutil is available before attempting enrollment.
if ! command -v mokutil >/dev/null 2>&1; then
    cat >&2 <<EOF

iExtend: SecureBoot is enabled but 'mokutil' is not installed.
         The evdi kernel module will not load until the signing key is enrolled.

         To fix:
           sudo apt-get install mokutil            # Debian/Ubuntu
           sudo dnf install mokutil               # Fedora/RHEL

         Then re-run:
           sudo /usr/share/iextend/dkms-mok-enrollment.sh

EOF
    exit 0
fi

# Interactive MOK enrollment prompt.
# This block runs synchronously; the actual enrollment completes on the NEXT
# reboot via the UEFI MOK Manager (blue shim screen).
cat <<EOF

  ════════════════════════════════════════════════════════════════
  iExtend: SecureBoot MOK Enrollment Required
  ════════════════════════════════════════════════════════════════

  The iExtend evdi kernel module is signed with iExtend's Machine
  Owner Key (MOK). To allow Linux to load it under SecureBoot, this
  key must be enrolled in your firmware — a one-time step.

  What will happen:
    1. We run:  mokutil --import ${MOK_DER}
    2. You will be prompted to create a TEMPORARY enrollment password.
       Choose anything memorable for the next reboot.
    3. REBOOT your computer.
    4. On reboot, a blue "MOK Management" screen appears.
       • Select "Enroll MOK"
       • Select "Continue"
       • Enter the password you chose above
       • Select "Yes" to confirm
       • Reboot again

  After step 4, the iExtend evdi module will load automatically on
  every boot.

  You can verify enrollment later with:
    mokutil --list-enrolled | grep -A 5 "iExtend"

  To skip enrollment now and do it later, press Ctrl+C.
  To re-run this script: sudo /usr/share/iextend/dkms-mok-enrollment.sh

  Press Enter to continue with MOK enrollment...
EOF

# In non-interactive contexts (e.g. CI, unattended install), skip if stdin is
# not a terminal.
if [ ! -t 0 ]; then
    echo "iExtend: stdin is not a terminal — skipping interactive MOK enrollment." >&2
    echo "         Run 'sudo /usr/share/iextend/dkms-mok-enrollment.sh' manually." >&2
    exit 0
fi

read -r _dummy

mokutil --import "$MOK_DER"

cat <<EOF

  MOK import queued. REBOOT NOW to complete enrollment.

  After reboot, verify with:
    mokutil --list-enrolled | grep -A 5 "iExtend"
  or:
    dmesg | grep -i "iextend\\|evdi\\|module.*signed"

EOF
